.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. glitch_qt test_glitch_qt
clean: FORCE
	$(MAKE) -C .. glitch_qt_clean test_glitch_qt_clean
check: FORCE
	$(MAKE) -C .. test_glitch_qt_check
glitch-qt glitch-qt.exe: FORCE
	 $(MAKE) -C .. glitch_qt
